from django.db import models

# Create your models here.
class DetailRegister(models.Model):
    name=models.CharField(max_length=100)
    age=models.CharField(max_length=10)
    height=models.CharField(max_length=10)
    religion=models.CharField(max_length=100)
    caste=models.CharField(max_length=100)
    location=models.CharField(max_length=100)
    education=models.CharField(max_length=100)
    profession=models.CharField(max_length=100)
    annualincome=models.CharField(max_length=100)    
    email=models.EmailField()
    password=models.CharField(max_length=100)
    image = models.ImageField(upload_to='img/')
    bodytype=models.CharField(max_length=100,default='SOME STRING')
    weight=models.CharField(max_length=100)
    mothertongue=models.CharField(max_length=100)
    maritalstatus=models.CharField(max_length=100)
    physicalstatus=models.CharField(max_length=100)
    eatinghabits=models.CharField(max_length=100)
    drinkinghabits=models.CharField(max_length=100)
    smokinghabits=models.CharField(max_length=100)
    contactnumber=models.CharField(max_length=100)
    parentcontact=models.CharField(max_length=100)
    star=models.CharField(max_length=100)
    country=models.CharField(max_length=100,default='SOME STRING')
    state=models.CharField(max_length=100)
    citizenship=models.CharField(max_length=100)
    dateofbirth=models.DateField(null=True, blank=True, default=None)
    placeofbirth=models.CharField(max_length=100)
    timeofbirth=models.CharField(max_length=100)
    forwho=models.CharField(max_length=100)
    partner=models.CharField(max_length=100)
    partnerage=models.CharField(max_length=100)
    partnerheight=models.CharField(max_length=100)
    partnermothertongue=models.CharField(max_length=100)
    partnerphysicalstatus=models.CharField(max_length=100)
    partnereatinghabits=models.CharField(max_length=100)
    partnersmokinghabits=models.CharField(max_length=100)
    partnerdrinkinghabits=models.CharField(max_length=100)
    partnereducation=models.CharField(max_length=100)
    partneroccupation=models.CharField(max_length=100)
    partnerannualincome=models.CharField(max_length=100)
    partnerreligion=models.CharField(max_length=100)
    partnercaste=models.CharField(max_length=100)
    partnerstar=models.CharField(max_length=100)
    partnercountry=models.CharField(max_length=100)
    partnerstate=models.CharField(max_length=100)
    partnercitizenship=models.CharField(max_length=100)
    partnercity=models.CharField(max_length=100)


   
    def __str__(self):
        return self.name